name: content_length_validator
description: Middleware for Shelf and Dart Frog to block too large requests.
version: 1.2.1
homepage: https://jxstxn.de
repository: https://github.com/jxstxn1/dart_content_length_validator
issue_tracker: https://github.com/jxstxn1/dart_content_length_validator/issues

topics:
  - shelf
  - security
  - dart-frog
  - middleware
  - content-length

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  shelf: ^1.3.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.24.0
