name: content_length_validator
description: Middleware for Shelf and Dart Frog to block too large requests.
version: 1.0.0+1
homepage: https://jxstxn.de
repository: https://github.com/jxstxn1/dart_content_length_validator

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  shelf: ^1.3.2

dev_dependencies:
  lint: ^1.0.0
  test: ^1.16.0
